### ISSUE TITLE
sl: License not found

### ISSUE THREAD

**Issue by fabioestevam** [bootlin/simplest-yocto-setup#4]
Hi,

I am getting the following warning when building the kiss-image:

```
WARNING: kiss-image-1.0-r0 do_rootfs: QA Issue: The license listed SL was not in the licenses collected for recipe sl [license-file-missing]
```

**Comment by lucaceresoli** [comment]
Thanks fr your report @fabioestevam, I just pushed a fix.

**Comment by fabioestevam** [comment]
Hi @lucaceresoli 

I pulled your fix, but still get the warning:

```
Build Configuration:
BB_VERSION           = "2.0.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "fedora-38"
TARGET_SYS           = "arm-oe-linux-gnueabi"
MACHINE              = "dogbonedark"
DISTRO               = "kiss"
DISTRO_VERSION       = "1.0"
TUNE_FEATURES        = "arm armv7a vfp thumb neon callconvention-hard"
TARGET_FPU           = "hard"
meta-arm             
meta-arm-toolchain   = "kirkstone:b187fb9232ca0a6b5f8f90b4715958546fc41d73"
meta-kiss            = "main:001d240ad47cf1f98567238fc5a60b4325d52a10"
meta                 = "kirkstone:8726ae02d760270f9e7fe7ef5715d8f7553371ce"

Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:01
Sstate summary: Wanted 7 Local 5 Mirrors 0 Missed 2 Current 656 (71% match, 99% complete)
Removing 1 stale sstate objects for arch dogbonedark: 100% |#################################################################################################################################| Time: 0:00:00
Removing 4 stale sstate objects for arch armv7at2hf-neon: 100% |#############################################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
WARNING: kiss-image-1.0-r0 do_rootfs: QA Issue: The license listed SL was not in the licenses collected for recipe sl [license-file-missing]
NOTE: Tasks Summary: Attempted 1796 tasks of which 1783 didn't need to be rerun and all succeeded.

Summary: There was 1 WARNING message.
```

**Comment by fabioestevam** [comment]
I ran:

```
bitbake kiss-image -c cleanall
bitbake kiss-image
```

And the QA warning is gone. Thanks
